# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on: [push]

jobs:
  publish_message_job:
    runs-on: ubuntu-latest
    name: A job to publish message to rabbitmq queue with headers
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
      - name: Publish message step
        uses: ./ # Uses an action in the root directory
        id: publish_message
        with:
          MESSAGE: "Test message"
          QUEUENAME: "test-rabbit-queue"
          HEADERS: "test-header1:testheader1val;test-header2:testheader2val"
          RABBITMQ_HOST: "34.225.202.16:5672"
          RABBITMQ_USERNAME: "chandula"
          RABBITMQ_PASSWORD: "F13Works!"
